[project]
name = "flappy-bird"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.6.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
flappy-bird = "main:main"
eval-mlp = "main:main_mlp"
eval-gru = "main:main_gru"
eval-lstm = "main:main_lstm"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["main"]

[tool.setuptools.packages.find]
where = ["."]
include = ["models*", "src*", "game*"]
namespaces = true
